apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.metadata.name }}
  namespace: {{ .Values.application.metadata.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.application.metadata.name }}-project
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: helm-guestbook
  destination:
    server: {{ .Values.application.spec.destination.server }}
    namespace: {{ .Values.application.spec.destination.namespace }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas