replicaCount: 1

image:
  name: eugene70/my-web-service
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  nodePort: 30080
  port: 8080
  targetPort: 8080

ingress:
  enabled: false

resources: {}
