apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.metadata.name }}
  namespace: {{ .Values.application.metadata.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: guestbook-project

  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: helm-guestbook

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.application.spec.destination.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  revisionHistoryLimit: 10
