apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: {{ .Values.service.port.name }}
      port: {{ .Values.service.port.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port.targetPort }}
      nodePort: {{ .Values.service.port.nodePort }}
  type: {{ .Values.service.type }}