{{- if .Values.service.enabled -}} # 서비스 생성 여부

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }} # 서비스가 노출할 port (cluster 내부 기준)
      targetPort: {{ .Values.app.container.port }} # 컨테이너가 listen 중인 port
      nodePort: {{ .Values.service.nodePort }} # 외부에서 접근할 포트, NodePort 타입일 때만 사용
  # Selector로 서비스가 연결할 Pod를 지정
  selector:
    app: {{ .Values.app.name }}
{{- end -}}