project:
  sourceRepos:
    - https://github.com/argoproj/argocd-example-apps.git
  destinations:
    - namespace: guestbook
      server: https://kubernetes.default.svc

application:
  metadata:
    name: guestbook
    namespace: argocd
  spec:
    destination:
      namespace: guestbook
