apiVersion: v2
name: charts
version: 0.1.0
appVersion: 0.1.0
kubeVersion: ">= 1.27.0"
description: "bianbbc87 helm chart chart.yaml"
home: https://chart.bianbbc87.com
maintainers:
  - name: bianbbc87
    email: bianbbc87@gmail.com