app:
  name: argicd-api
  replicas: 1
  image: beer1/todo-server-kotlin:0.1.0
  port: 9000
  customCommand: []
  customArgs: []
  env: []
  resources: {}

podAnnotations: {}
podLabels: {}

probes:
  readiness: {}
  liveness: {}

rbac:
  enabled: false

service:
  enabled: true
  port: 80