apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "charts.selectorLabels" . }}
  template:
    metadata:
      labels:
        {{- include "charts.labels" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}"
          ports:
            - containerPort: {{ .Values.service.port }}