name: Build Image

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # -
      #   name: Checkout
      #   uses: actions/checkout@v2
      # -
      #   name: CheckDir
      #   working-directory: ./${{ github.actor }}
      #   run: ls -al
      # -
      #   name: Docker meta
      #   id: docker_meta
      #   uses: crazy-max/ghaction-docker-meta@v1
      #   with:
      #     images: teichae/node
      #     tag-semver: |
      #       {{version}}
      #       {{major}}.{{minor}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Container Image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:${{ github.actor }}"
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          tags: test:latest