name: Build Image

env:
  YEAR: 2025
  IMAGE_NAME: helm-test

on:

  push:
    paths:
      - '20*/helm/**'
      - '20*/argo-cd/**'
  pull_request:
    paths:
      - '20*/helm/**'
      - '20*/argo-cd/**'

jobs:
  prepare:
    name: Prepare Job
    runs-on: ubuntu-latest
    outputs:
      run_helm: ${{ steps.filter.outputs.helm }}
      run_argo: ${{ steps.filter.outputs.argo }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            helm:
              - '20*/helm/**'
            argo:
              - '20*/argo-cd/**'
  
  helm-test:
    name: Helm Test
    env:
      HELM_TEST_CLUSTER_NAME: helm-e2e
    needs: prepare
    if: needs.prepare.outputs.run_helm == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Kind Cluster Config
        run: |
          echo "kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          name: $HELM_TEST_CLUSTER_NAME
          nodes:
          - role: control-plane
            extraPortMappings:
            - containerPort: 30080
              hostPort: 30080" >> config.yaml
      
      - name: create kind cluster
        uses: helm/kind-action@v1.9.0
        with:
          cluster_name: helm-e2e
          config: ./config.yaml

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Prepare Docker build Context
        id: ctx
        run: |
          echo "context=${{ env.YEAR }}/helm/${{ github.actor }}" >> $GITHUB_OUTPUT
          echo "tag=${{ env.IMAGE_NAME }}:${{ github.actor }}" >> $GITHUB_OUTPUT

      - name: Build Container Image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ steps.ctx.outputs.context }}"
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          tags: ${{ steps.ctx.outputs.tag }}
          load: true

      - name: Image Upload to Kind
        run: |
          kind load docker-image ${{ steps.ctx.outputs.tag }} --name $HELM_TEST_CLUSTER_NAME

      - name: Deployment Simple App
        run: |
          cd ${{ steps.ctx.outputs.context }}
          helm install --wait --set image.name=${{ steps.ctx.outputs.tag }} ossca-test ./charts

      - name: Check Deployment Success
        run: |
          docker ps
          kubectl get pod --show-labels -o wide
          kubectl get svc -o wide
          curl -v localhost:30080/healthcheck

  argocd-test:
    name: ArgoCD Test
    needs: prepare
    if: needs.preare.outputs.run_argo == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: create kind cluster
        uses: helm/kind-action@v1.9.0
        with:
          cluster_name: argocd-e2e